export const siteConfig = {
  name: "26KADO",
  slogan: "Le meilleur programme d'affiliation des bookmakers en Afrique",
  description:
    "26KADO est la plateforme N°1 d'affiliation des bookmakers en Afrique. Promouvez les codes promo 1xBet, BetWinner, MelBet, LineBet et gagnez des commissions exclusives.",
  url: "https://26kado.com",
  ogImage: "https://26kado.com/og.jpg",
  links: {
    twitter: "https://twitter.com/26kado",
    whatsapp: "https://chat.whatsapp.com/26kado",
    telegram: "https://t.me/26kado",
  },
  promoCode: "26KADO",
  promoCodeDls3: "DLS3",
  bookmakers: [
    {
      name: "1xBet",
      slug: "1xbet",
      color: "#1a5cff",
      bonus: "100% jusqu'à 200 000 FCFA",
      promoCode: "26KADO",
    },
    {
      name: "BetWinner",
      slug: "betwinner",
      color: "#ff6b00",
      bonus: "100% jusqu'à 150 000 FCFA",
      promoCode: "26KADO",
    },
    {
      name: "MelBet",
      slug: "melbet",
      color: "#ffd700",
      bonus: "100% jusqu'à 175 000 FCFA",
      promoCode: "26KADO",
    },
    {
      name: "LineBet",
      slug: "linebet",
      color: "#00e676",
      bonus: "100% jusqu'à 130 000 FCFA",
      promoCode: "26KADO",
    },
  ],
  bookmakersDls3: [
    {
      name: "1xBet",
      slug: "1xbet",
      color: "#1a5cff",
      bonus: "100% jusqu'à 200 000 FCFA",
      promoCode: "DLS3",
    },
    {
      name: "BetWinner",
      slug: "betwinner",
      color: "#ff6b00",
      bonus: "100% jusqu'à 150 000 FCFA",
      promoCode: "DLS3",
    },
    {
      name: "MelBet",
      slug: "melbet",
      color: "#ffd700",
      bonus: "100% jusqu'à 175 000 FCFA",
      promoCode: "DLS3",
    },
    {
      name: "LineBet",
      slug: "linebet",
      color: "#00e676",
      bonus: "100% jusqu'à 130 000 FCFA",
      promoCode: "DLS3",
    },
  ],
  advantages: [
    {
      title: "Bonus Exclusifs",
      description: "Profitez des meilleures offres de bonus réservées à nos ambassadeurs.",
      icon: "Gift",
    },
    {
      title: "Support Premium",
      description: "Une équipe dédiée disponible 7j/7 pour vous accompagner.",
      icon: "Headphones",
    },
    {
      title: "Coupons Gratuits",
      description: "Recevez des coupons WhatsApp chaque jour pour maximiser vos gains.",
      icon: "Ticket",
    },
    {
      title: "Programme Ambassadeur",
      description: "Devenez ambassadeur et gagnez 10% sur les commissions de vos filleuls.",
      icon: "Users",
    },
    {
      title: "Commissions Élevées",
      description: "Les meilleurs taux de commission du marché africain.",
      icon: "TrendingUp",
    },
    {
      title: "Paiements Rapides",
      description: "Recevez vos commissions en 24h après validation.",
      icon: "Zap",
    },
  ],
  steps: [
    {
      step: 1,
      title: "Créer un compte",
      description: "Inscrivez-vous gratuitement sur 26KADO en quelques secondes.",
    },
    {
      step: 2,
      title: "Choisir un bookmaker",
      description: "Sélectionnez parmi 1xBet, BetWinner, MelBet ou LineBet.",
    },
    {
      step: 3,
      title: "Utiliser le code 26KADO",
      description: "Utilisez notre code promo lors de votre inscription.",
    },
    {
      step: 4,
      title: "Faire le premier dépôt",
      description: "Effectuez votre premier dépôt pour activer le bonus.",
    },
    {
      step: 5,
      title: "Envoyer les preuves",
      description: "Téléchargez vos captures d'écran d'inscription et de dépôt.",
    },
    {
      step: 6,
      title: "Recevoir votre commission",
      description: "Votre commission est créditée automatiquement sur votre wallet.",
    },
  ],
  navigation: [
    { title: "Accueil", href: "/" },
    { title: "Guide", href: "/guide" },
    { title: "Bookmakers", href: "/bookmakers" },
    { title: "À propos", href: "/about" },
    { title: "FAQ", href: "/faq" },
    { title: "Classement", href: "/leaderboard" },
    { title: "Contact", href: "/support" },
  ],
  dashboardNavigation: [
    { title: "Tableau de bord", href: "/dashboard", icon: "LayoutDashboard" },
    { title: "Commissions", href: "/dashboard/commissions", icon: "Coins" },
    { title: "Portefeuille", href: "/dashboard/wallet", icon: "Wallet" },
    { title: "Retrait", href: "/dashboard/retrait", icon: "ArrowUpFromLine" },
    { title: "Validations", href: "/dashboard/validations", icon: "Upload" },
    { title: "Parrainages", href: "/dashboard/referrals", icon: "Users" },
    { title: "Support", href: "/dashboard/support", icon: "Headphones" },
    { title: "Ressources", href: "/dashboard/resources", icon: "BookOpen" },
    { title: "Notifications", href: "/dashboard/notifications", icon: "Bell" },
  ],
  adminNavigation: [
    { title: "Dashboard", href: "/admin", icon: "LayoutDashboard" },
    { title: "Utilisateurs", href: "/admin/users", icon: "Users" },
    { title: "Bookmakers", href: "/admin/bookmakers", icon: "Gamepad2" },
    { title: "Validations", href: "/admin/validations", icon: "Upload" },
    { title: "Commissions", href: "/admin/commissions", icon: "Coins" },
    { title: "Paiements", href: "/admin/payments", icon: "CreditCard" },
    { title: "Dépôt", href: "/admin/deposit", icon: "ArrowDownToLine" },
    { title: "Retraits", href: "/admin/withdrawals", icon: "ArrowUpFromLine" },
    { title: "Tickets", href: "/admin/tickets", icon: "Headphones" },
    { title: "FAQ", href: "/admin/faq", icon: "HelpCircle" },
    { title: "Badges", href: "/admin/badges", icon: "Award" },
    { title: "Niveaux", href: "/admin/levels", icon: "BarChart3" },
    { title: "Classement", href: "/admin/leaderboard", icon: "Trophy" },
    { title: "WhatsApp", href: "/admin/whatsapp", icon: "MessageCircle" },
    { title: "Ressources", href: "/admin/resources", icon: "BookOpen" },
    { title: "Notifications", href: "/admin/notifications", icon: "Bell" },
    { title: "Logs", href: "/admin/logs", icon: "ScrollText" },
    { title: "Paramètres", href: "/admin/settings", icon: "Settings" },
  ],
};

export type SiteConfig = typeof siteConfig;